name: CI
on: [push]
jobs:
  test_build_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - name: Run tests
        run: |
          pip install pytest
          pytest
          pytest
      # - name: build docker image
      #   run: |
      #     docker build -t test .
      # - name: run docker image
      #   run: |
      #     docker run test